version = 1

test_patterns = [
  "/src/Framework.UnitTests/**/*.cs",
  "/src/Utilities.UnitTests/**/*.cs"
]

exclude_patterns = [
  "src/Tasks/**/*.cs"
]

[[analyzers]]
name = "csharp"
enabled = true
